dist: trusty
language: java
script: mvn verify -Pquality,linux
cache:
  directories:
  - ~/.m2/repository
deploy:
  provider: script
  edge: true
  script: travis/deploy.sh
  on:
    branch: testdeployment


