dist: trusty
language: java
jdk:
  - openjdk8
  - openjdk11
script: cd system-tests/ft-suite && mvn verify -Pquality,linux -Dit.test=OriginsFileCompatibilitySpec
cache:
  directories:
  - ~/.m2/repository
