dist: trusty
language: java
script: mvn help:effective-settings
cache:
  directories:
  - "~/.m2/repository"
deploy:
- provider: script
  script: travis/deploy.sh
  skip_cleanup: true
  on:
    branch: testdeployment
- provider: script
  script: travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: "./distribution/target/styx-*.zip"
  skip_cleanup: true
  on:
    tags: true